/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ADMON
 */
public class Frm_Principiante extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Principiante
     */
    public Frm_Principiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lbl_Suma1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Lbl_Suma2 = new javax.swing.JLabel();
        Lbl_Suma3 = new javax.swing.JLabel();
        Lbl_Suma4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Txt_Suma1 = new javax.swing.JTextField();
        Txt_Suma2 = new javax.swing.JTextField();
        Lbl_Resta1 = new javax.swing.JLabel();
        Lbl_Resta2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Lbl_Resta3 = new javax.swing.JLabel();
        Lbl_Resta4 = new javax.swing.JLabel();
        Txt_Resta1 = new javax.swing.JTextField();
        Txt_Resta2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Lbl_Divi1 = new javax.swing.JLabel();
        Lbl_Divi2 = new javax.swing.JLabel();
        Txt_Multi = new javax.swing.JTextField();
        Txt_Divi = new javax.swing.JTextField();
        Lbl_Multi1 = new javax.swing.JLabel();
        Lbl_Multi2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Txt_RestaR1 = new javax.swing.JTextField();
        Txt_RestaR2 = new javax.swing.JTextField();
        Txt_MultiR1 = new javax.swing.JTextField();
        Txt_DiviR1 = new javax.swing.JTextField();
        Txt_SumaR1 = new javax.swing.JTextField();
        Txt_SumaR2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(808, 416));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("OPERACIONES MATEMÁTICAS");

        jLabel2.setText("CONFIRME LOS VALORES DE LAS SIGUIENTES OPERACIONES");

        Lbl_Suma1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Suma1.setText("NUM1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("+");

        Lbl_Suma2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Suma2.setText("NUM2");

        Lbl_Suma3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Suma3.setText("NUM1");

        Lbl_Suma4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Suma4.setText("NUM2");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("+");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("OP1.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("OP2.");

        Lbl_Resta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Resta1.setText("NUM1");

        Lbl_Resta2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Resta2.setText("NUM2");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("-");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("OP2.");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("-");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("OP2.");

        Lbl_Resta3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Resta3.setText("NUM1");

        Lbl_Resta4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Resta4.setText("NUM2");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("*");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("OP2.");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("/");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("OP2.");

        Lbl_Divi1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Divi1.setText("NUM1");

        Lbl_Divi2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Divi2.setText("NUM2");

        Lbl_Multi1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Multi1.setText("NUM1");

        Lbl_Multi2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Multi2.setText("NUM2");

        jButton1.setText("NUEVO");

        jButton2.setText("VALIDAR");

        Txt_RestaR1.setEditable(false);

        Txt_RestaR2.setEditable(false);

        Txt_MultiR1.setEditable(false);

        Txt_DiviR1.setEditable(false);

        Txt_SumaR1.setEditable(false);

        Txt_SumaR2.setEditable(false);

        jLabel3.setText("RESULTADOS");

        jLabel5.setText("INGRESE SUS");

        jLabel6.setText("VALORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(22, 22, 22)
                                        .addComponent(Lbl_Multi1)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(22, 22, 22)
                                        .addComponent(Lbl_Divi1)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel24)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_Divi2)
                                    .addComponent(Lbl_Multi2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_Multi)
                                    .addComponent(Txt_Divi)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lbl_Suma1)
                                            .addComponent(Lbl_Suma3))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel11)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(22, 22, 22)
                                        .addComponent(Lbl_Resta1)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(22, 22, 22)
                                        .addComponent(Lbl_Resta3)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel18)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_Resta4)
                                    .addComponent(Lbl_Resta2)
                                    .addComponent(Lbl_Suma4)
                                    .addComponent(Lbl_Suma2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_Resta2)
                                    .addComponent(Txt_Resta1)
                                    .addComponent(Txt_Suma2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(Txt_Suma1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel6)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Txt_MultiR1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_DiviR1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_RestaR2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_RestaR1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_SumaR1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(Txt_SumaR2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_Suma1)
                            .addComponent(jLabel7)
                            .addComponent(Lbl_Suma2)
                            .addComponent(jLabel12)
                            .addComponent(Txt_Suma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lbl_Suma3)
                                    .addComponent(Lbl_Suma4)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(Txt_Suma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lbl_Resta1)
                                    .addComponent(Lbl_Resta2)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(Txt_Resta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lbl_Resta3)
                                    .addComponent(Lbl_Resta4)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(Txt_Resta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(90, 90, 90)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_Multi1)
                            .addComponent(Lbl_Multi2)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(Txt_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_MultiR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Txt_SumaR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(Txt_SumaR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(Txt_RestaR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(Txt_RestaR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Divi1)
                    .addComponent(Lbl_Divi2)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(Txt_Divi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_DiviR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Principiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Divi1;
    private javax.swing.JLabel Lbl_Divi2;
    private javax.swing.JLabel Lbl_Multi1;
    private javax.swing.JLabel Lbl_Multi2;
    private javax.swing.JLabel Lbl_Resta1;
    private javax.swing.JLabel Lbl_Resta2;
    private javax.swing.JLabel Lbl_Resta3;
    private javax.swing.JLabel Lbl_Resta4;
    private javax.swing.JLabel Lbl_Suma1;
    private javax.swing.JLabel Lbl_Suma2;
    private javax.swing.JLabel Lbl_Suma3;
    private javax.swing.JLabel Lbl_Suma4;
    private javax.swing.JTextField Txt_Divi;
    private javax.swing.JTextField Txt_DiviR1;
    private javax.swing.JTextField Txt_Multi;
    private javax.swing.JTextField Txt_MultiR1;
    private javax.swing.JTextField Txt_Resta1;
    private javax.swing.JTextField Txt_Resta2;
    private javax.swing.JTextField Txt_RestaR1;
    private javax.swing.JTextField Txt_RestaR2;
    private javax.swing.JTextField Txt_Suma1;
    private javax.swing.JTextField Txt_Suma2;
    private javax.swing.JTextField Txt_SumaR1;
    private javax.swing.JTextField Txt_SumaR2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
