/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ADMON
 */
public class Frm_Intermedio extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Intermedio
     */
    public Frm_Intermedio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Txt_n1 = new javax.swing.JLabel();
        Txt_n2 = new javax.swing.JLabel();
        Txt_n3 = new javax.swing.JLabel();
        Txt_n4 = new javax.swing.JLabel();
        Txt_n5 = new javax.swing.JLabel();
        Lbl_pregunta1 = new javax.swing.JLabel();
        Lbl_pregunta2 = new javax.swing.JLabel();
        Lbl_pregunta3 = new javax.swing.JLabel();
        Lbl_pregunta4 = new javax.swing.JLabel();
        Lbl_pregunta5 = new javax.swing.JLabel();
        Cbx_1 = new javax.swing.JComboBox<>();
        Cbx_2 = new javax.swing.JComboBox<>();
        Cbx_3 = new javax.swing.JComboBox<>();
        Cbx_4 = new javax.swing.JComboBox<>();
        Cbx_5 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(808, 416));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SELECCIONE LA RESPUESTA QUE CONSIDERE CORRECTA");

        Txt_n1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_n1.setText("1");

        Txt_n2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_n2.setText("2");

        Txt_n3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_n3.setText("3");

        Txt_n4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_n4.setText("4");

        Txt_n5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_n5.setText("5");

        Lbl_pregunta1.setText("jLabel7");

        Lbl_pregunta2.setText("jLabel8");

        Lbl_pregunta3.setText("jLabel9");

        Lbl_pregunta4.setText("jLabel10");

        Lbl_pregunta5.setText("jLabel11");

        Cbx_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EL GRAN JAGUAR", "LA DANTA", "TEMPLO IV" }));

        Cbx_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MIGUEL ANGEL ASTURIAS", "EFRAIN RECINOS", "MANOLO GALLARDO" }));

        Cbx_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JORGE UBICO", "RAFAEL ALVAREZ OVALLE", "RICARDO ANDRADE" }));

        Cbx_4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TAJUMULCO", "ACATENANGO", "TACANA" }));

        Cbx_5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GUILLERMO DE LEON", "DAVID VELA", "FRANCISCO PEREZ" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Txt_n3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_pregunta3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Txt_n2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_pregunta2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Txt_n1)
                            .addGap(49, 49, 49)
                            .addComponent(Lbl_pregunta1)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_n4)
                            .addComponent(Txt_n5))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_pregunta5)
                            .addComponent(Lbl_pregunta4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cbx_1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cbx_2, 0, 200, Short.MAX_VALUE)
                    .addComponent(Cbx_3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cbx_4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cbx_5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_n1)
                    .addComponent(Lbl_pregunta1)
                    .addComponent(Cbx_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_n2)
                    .addComponent(Lbl_pregunta2)
                    .addComponent(Cbx_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_n3)
                    .addComponent(Lbl_pregunta3)
                    .addComponent(Cbx_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_n4)
                    .addComponent(Lbl_pregunta4)
                    .addComponent(Cbx_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_n5)
                    .addComponent(Lbl_pregunta5)
                    .addComponent(Cbx_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Intermedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbx_1;
    private javax.swing.JComboBox<String> Cbx_2;
    private javax.swing.JComboBox<String> Cbx_3;
    private javax.swing.JComboBox<String> Cbx_4;
    private javax.swing.JComboBox<String> Cbx_5;
    private javax.swing.JLabel Lbl_pregunta1;
    private javax.swing.JLabel Lbl_pregunta2;
    private javax.swing.JLabel Lbl_pregunta3;
    private javax.swing.JLabel Lbl_pregunta4;
    private javax.swing.JLabel Lbl_pregunta5;
    private javax.swing.JLabel Txt_n1;
    private javax.swing.JLabel Txt_n2;
    private javax.swing.JLabel Txt_n3;
    private javax.swing.JLabel Txt_n4;
    private javax.swing.JLabel Txt_n5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
